# Site settings
title: jakrig
email: k.hoenselaers@gmail.com
description: >
    jakrig : Rigging, Pipeline and Technical Animation.
baseurl:
url: http://k-rig.co.uk

# Build settings
markdown: kramdown


highlighter: rouge

collections:
  projects:
    output: true
    permalink: /projects/:path/
    
exclude: [serve.sh, build.sh, Gemfile, Gemfile.lock]